# Generated by Django 4.0.5 on 2022-06-29 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(choices=[('f', 'Food'), ('d', 'Drink')], default='f', help_text='Dish type', max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField()),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'close')], default='o', help_text='Status', max_length=1)),
                ('dish', models.ManyToManyField(help_text='Select dish for this Menu', to='poll.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('dish_name', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vote_as', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.menu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_name', 'dish_name'],
            },
        ),
    ]
