# Generated by Django 4.0.5 on 2022-07-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['user_name', 'dish_name']},
        ),
        migrations.AddField(
            model_name='vote',
            name='dish_name',
            field=models.CharField(blank=True, choices=[], help_text='Dish', max_length=300, null=True),
        ),
    ]
