# Generated by Django 4.0.5 on 2022-06-29 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Vote',
        ),
    ]
