# Generated by Django 4.0.5 on 2022-08-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_vote_options_vote_dish_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at', 'dish_name']},
        ),
        migrations.AlterField(
            model_name='vote',
            name='dish_name',
            field=models.CharField(blank=True, choices=[('Bún chả', 'Bún chả'), ('Cà phê', 'Cà phê'), ('Cơm tấm', 'Cơm tấm'), ('Cơm xá xíu', 'Cơm xá xíu'), ('Thịt chó', 'Thịt chó')], help_text='Dish', max_length=300, null=True),
        ),
    ]
