# Generated by Django 4.0.5 on 2022-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_rename_action_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_as',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
