# Generated by Django 4.0.5 on 2022-07-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_vote_vote_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='dish_name',
            field=models.CharField(blank=True, choices=[('Hotdog', 'Hotdog'), ('Mì vằn thắn', 'Mì vằn thắn'), ('Ramen', 'Ramen')], help_text='Dish', max_length=300, null=True),
        ),
    ]
