# Generated by Django 4.0.5 on 2022-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_vote_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='dish_name',
            field=models.CharField(blank=True, choices=[('Bánh mỳ pate', 'Bánh mỳ pate'), ('Bún bò Huế', 'Bún bò Huế'), ('Cà phê', 'Cà phê'), ('Hotdog', 'Hotdog'), ('Mì vằn thắn', 'Mì vằn thắn'), ('Phở bò Nam Định', 'Phở bò Nam Định'), ('Ramen', 'Ramen'), ('Trà đá', 'Trà đá')], help_text='Dish', max_length=300, null=True),
        ),
    ]
