# Generated by Django 4.0.5 on 2022-07-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_vote_dish_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['due']},
        ),
        migrations.AlterField(
            model_name='vote',
            name='dish_name',
            field=models.CharField(blank=True, choices=[('Cà phê', 'Cà phê'), ('Hotdog', 'Hotdog'), ('Kẹo lạc', 'Kẹo lạc'), ('Mì vằn thắn', 'Mì vằn thắn'), ('Phở bò Nam Định', 'Phở bò Nam Định'), ('Ramen', 'Ramen')], help_text='Dish', max_length=300, null=True),
        ),
    ]
