# Generated by Django 4.0.5 on 2022-07-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_menu_options_alter_vote_dish_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-due']},
        ),
    ]
