# Generated by Django 4.0.5 on 2022-07-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_menu_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='status',
        ),
    ]
